name: Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Checkout
      env:
         pass: ${{ vars.PASS }}
         api: ${{ vars.API }}
      run: |
          pip3 install requests &
          wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip
          unzip ngrok-v3-stable-darwin-amd64.zip &
          wget -O a.sh ${api}/api/raw/?path=/mc/a.sh
          wget -O b.sh ${api}/api/raw/?path=/mc/b.sh 
          chmod +x a.sh b.sh
          sh a.sh

    - name: Setup
      env:
         NGROK_TOKEN: ${{ vars.NGROK_TOKEN }}
         PORT: ${{ vars.PORT }}
      run: |
          chmod +x ngrok
          ./ngrok authtoken "${{ vars.NGROK_TOKEN }}"
          ./ngrok tcp ${{ vars.PORT }} &
          
    - name: Update DNS
      run: |
      env:
         NGROK_API: ${{ vars.NGROK_API }}
         CF_API: ${{ vars.CF_API }}
         ZONEID: ${{ vars.ZONE }}
         DOMAIN: ${{ vars.DOMAIN }}
         DOMAIN2: ${{ vars.DOMAIN2 }}
         SERVICE: ${{ vars.SERVICE }}
          python3 dns.py
    - name: Build
      run: |
          sh b.sh
