name: Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      uses: Mattraks/delete-workflow-runs@v2.0.3
      with:
        retain_days: 0
        keep_minimum_runs: 2
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Checkout
      env:
         pass: ${{ env.PASS }}
         api: ${{ env.API }}
      run: |
          pip3 install requests &
          wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip
          unzip ngrok-v3-stable-darwin-amd64.zip &
          wget -O a.sh ${{ env.API }}api/raw/?path=/mc/a.sh
          wget -O b.sh ${{ env.API }}api/raw/?path=/mc/b.sh 
          chmod +x a.sh b.sh
          sh a.sh

    - name: Setup
      env:
         NGROK_TOKEN: ${{ env.NGROK_TOKEN }}
         PORT: ${{ env.PORT }}
      run: |
          chmod +x ngrok
          ./ngrok authtoken "${{ env.NGROK_TOKEN }}"
          ./ngrok tcp ${{ env.PORT }} &
          
    - name: Update DNS
      run: |
      env:
         NGROK_API: ${{ env.NGROK_API }}
         CF_API: ${{ env.CF_API }}
         ZONEID: ${{ env.ZONE }}
         DOMAIN: ${{ env.DOMAIN }}
         DOMAIN2: ${{ env.DOMAIN2 }}
         SERVICE: ${{ env.SERVICE }}
          python3 dns.py
    - name: Build
      run: |
          sh b.sh
